### ISSUE TITLE
Upload jsch-agent-proxy to maven repository

### ISSUE THREAD

**Issue by mamciek** [ymnk/jsch-agent-proxy#1]
Please upload jsch-agent-proxy jars to Maven Repository

**Comment by mlhartme** [comment]
jsch-agent-proxy worked fine for me - please make it available on Maven Central!

**Comment by ymnk** [comment]
Could you try the following branch at
  https://github.com/ymnk/jsch-agent-proxy/tree/feature/add_pom.xml

  $ cd jsch-agent-proxy
  $ mvn package
  $ mvn install

As for configurations for pom.xml, refer to examples/pom.xml .

If there is not a problem, we will try to deploy it to Maven Central.

**Comment by mlhartme** [comment]
It works for me :)

I struggled a bit, because my parent pom rejects duplikate classes in the dependency tree, i had to exclude your Core module from your dependencies. From my perspective, i'd prefer not to bundle Core into the other modules ... 

Thank you very much!

Michael

**Comment by ymnk** [comment]
> I struggled a bit, because my parent pom rejects duplikate classes in the dependency tree, 
> i had to exclude your Core module from your dependencies.

It is helpful to understand your problem if you provide me sample code to reproduce it.

**Comment by mlhartme** [comment]
You can reproduce it by cloning git@github.com:mlhartme/sushi.git, remove the exclusions from the jsch agent dependencies in pom.xml and run mvn package.

The enforcer rule that detects duplicate classes is Company specific. Checking this is not done by many people - but we consider it good practice to ban duplicate classes. Because they can differ and cause strange problems 

Having these exclusions works for me as a work-around, so this problem is not a blocker for me.

**Comment by ymnk** [comment]
> You can reproduce it by cloning git@github.com:mlhartme/sushi.git, remove the exclusions
> from the jsch agent dependencies in pom.xml and run mvn package.

I could reproduce your problem, and I have modified its pom.xml.
Could you try it again?

**Comment by mlhartme** [comment]
I have only my Handy until Sunday - i'll try then. 

Am 26.12.2012 um 11:12 schrieb Atsuhiko Yamanaka notifications@github.com:

**Comment by mlhartme** [comment]
Works fine now, thank you!

**Comment by ymnk** [comment]
> Works fine now, thank you!

I really appreciate your cooperation.
I'll try to deploy that version  to the maven central.

**Comment by ymnk** [comment]
It has appeared on the central repository.

Please note that its groupId has been changed to "com.jcraft", as  suggested in the comment

```
https://issues.sonatype.org/browse/OSSRH-5126?focusedCommentId=178410&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-178410
```

As for configurations of artifactId and version number, please refer to 

```
http://github.com/ymnk/jsch-agent-proxy/blob/master/examples/pom.xml#L12
```

**Comment by mlhartme** [comment]
0.0.5 works fine :)

By the way: as far as I understand, your Sonatype OSS account allows you to deploy to groupId "com.jcraft" and anything below. Thus, it would have been possible do use com.jcarft.jsch or com.jcarft.jsch.agentproxy as your groupId.

Best Regards

Michael
