### ISSUE TITLE
example filenames don't line up with package names

### ISSUE THREAD

**Issue by charles-dyfis-net** [ymnk/jsch-agent-proxy#11]
The examples declare that they are in package `com.jcraft.jsch.agentproxy.examples`, but are located under `com/jcraft/agentproxy/examples` (with no `jsch` in the name).

**Comment by charles-dyfis-net** [comment]
One resolution (putting the `jsch` in the name everywhere) is at 52fc362c0fecd18201b4c0d36275cd703f040730

**Comment by ymnk** [comment]
It has been fixed, https://github.com/ymnk/jsch-agent-proxy/commit/d95775f53ebdb5400f489473114daad023bf72f7.
