### ISSUE TITLE
Publish artifacts to a maven repository

### ISSUE THREAD

**Issue by Khoulaiz** [ymnk/jsch-agent-proxy#18]
Doesn't matter where, eg. bintray jcenter would be ok, too
I know I can easily build the project but it would be way more convenient just to grab it from the internet.

I am trying to use this lib in a gradle build script. If the packages would be released in a maven repo, I could easily write build scripts that run everywhere. But without release in a repo, I either have to put the lib into every project that is using it :-( or my scripts will run only in specific environments (with a private repo that contains the lib).

**Comment by ymnk** [comment]
It is available at the maven central repo.  Please refer to http://mvnrepository.com/artifact/com.jcraft/jsch.agentproxy

**Comment by Khoulaiz** [comment]
Ahh, that's great, thanks. It's hard to find because of the different project naming. (with dashes, without dashes, with dot etc.)
