### ISSUE TITLE
Support sshj

### ISSUE THREAD

**Issue by hugoduncan** [ymnk/jsch-agent-proxy#2]
Would be great to see ssh agent support in https://github.com/shikhar/sshj

See https://github.com/shikhar/sshj/issues/33 for the corresponding issue in sshj,

**Comment by ymnk** [comment]
It will be easy to use jsch-agent-proxy in sshj, and it will be acceptable because it has already adopted our jzlib.
FYI, net-ssh for JRuby has adopted it, 
  https://github.com/net-ssh/net-ssh/pull/35

**Comment by ymnk** [comment]
liff, thank you for your contribution.  I'll wait for a green light at https://github.com/shikhar/sshj/issues/33#issuecomment-16989186 .

**Comment by ymnk** [comment]
The contribution from liff has been merged.
