### ISSUE TITLE
Publish 0.0.9 including usocket_path merge?

### ISSUE THREAD

**Issue by mathpl** [ymnk/jsch-agent-proxy#21]
Hi Atsuhiko, sorry to bother you with this but would it be possible to publish a new version of jsch-agent-proxy that includes a merge of the usocket_path branch?

Thank you very much!

**Comment by ymnk** [comment]
That branch has been merged to tahe master branch,
and it will appear at the maven central repository soon.

**Comment by mathpl** [comment]
Got it, thank you very much!
