### ISSUE TITLE
Not able to set SSH agent

### ISSUE THREAD

**Issue by ghost** [ymnk/jsch-agent-proxy#25]
I got aware of this project after reading this issue in Eclipse's Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=179924

First of all, thank you very much for putting so much afford into creating this, I really appreciate it.
After reading your commment (https://bugs.eclipse.org/bugs/show_bug.cgi?id=179924#c86), I tried installing it through the Eclipse "Install new software" option and chose your ssh-agent proxy. Everything went just fine, at least there was no error...
Unfortunately, I am not able to set anything under General > ... > SSH Agent, since the window doesn't offer anything to be checked.

Here is a screenshot of the installed plugin:

![1](https://cloud.githubusercontent.com/assets/13337480/9423548/6d0679e8-48c8-11e5-999a-efc66e32cf2c.png)

Here is a screenshot of the SSH Agent window:

![2](https://cloud.githubusercontent.com/assets/13337480/9423550/7e10bb72-48c8-11e5-9a9d-376978747b62.png)

I am using Eclipse Mars 4.5 on Ubuntu 15.04. 
Both Eclipse and Ubuntu were restarted several times.
If you need more information, please let me know.

**Comment by guw** [comment]
Can you try with Neon with the version published here:
https://eclipseguru.github.io/eclipse-jsch-agent-proxy/

**Comment by ghost** [comment]
Sorry, I am not using the plug-in anymore. I will close this now
