### ISSUE TITLE
AgentProxy is not thread safe

### ISSUE THREAD

**Issue by hugoduncan** [ymnk/jsch-agent-proxy#5]
All functions in AgentProxy share an instance Buffer object,  making it unsafe to access the agent, even just for query functions such as getIdentities, from multiple threads.

**Comment by ymnk** [comment]
Thank you for your suggestion.  I agree it should be thread safe, and the code has modified,
  https://github.com/ymnk/jsch-agent-proxy/commit/d69463280a562750ad573373b3db898f35a66f48
